
services:
  storage-node-server:
    build: .
    volumes:
      - ./shared:/shared
    ports:
      - "2222:22"  # Expose SSH port for rsync
    # Optional: Add environment variables if needed for the server

  storage-node-client:
    build:
      context: .
      dockerfile: Dockerfile.storage
    privileged: true
    network_mode: host  # Use host networking to avoid port conflicts
    environment:
      - ZEROTIER_NETWORK_ID=${ZEROTIER_NETWORK_ID}
      - NODE_NAME=${NODE_NAME:-storage1}
      - SYNCTHING_UID=1000
      - SYNCTHING_GID=1000
      - USERNAME=${USERNAME}
      - SHARED_DIR=${SHARED_DIR}
#      - CRON_TASK_1="0 1 * * * /data/pack-db.sh"
#      - CRON_TASK_2="0 3 * * * /bin/sh -c 'rsync -e \"ssh -p 2222 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null\" -aqx --numeric-ids rpi@<remote_server_ip>:/shared/ /shared/'"
    volumes:
      - ./shared:/shared
      - ${BACKUP_SYNC_PATH:-./backups}:/backups
      - ${PUBLIC_SHARE_PATH:-./public}:/public
      - ./config/syncthing/${NODE_NAME:-storage1}:/etc/syncthing
      - ./config/samba/${NODE_NAME:-storage1}/:/etc/samba/
      - ./config/nfs/${NODE_NAME:-storage1}:/etc/exports.d
      - ./config/mosquitto/${NODE_NAME:-storage1}/mosquitto.conf:/etc/mosquitto/conf.d/
      - ./config/zerotier/${NODE_NAME:-storage1}:/var/lib/zerotier-one
      - ./config/mosquitto/${NODE_NAME:-storage1}/data:/var/lib/mosquitto
      - ./config/mosquitto/${NODE_NAME:-storage1}/log:/var/log/mosquitto
      - ./config/samba/${NODE_NAME:-storage1}/log:/var/log/samba

    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW

    depends_on:
      - storage-node-server

#volumes:
#  shared_data:  shared

